name: Generate Chain Specs from Node Binary 

on:
  workflow_call:
    inputs:
      sha:
        description: 'Commit SHA to append to chain spec secret name'
        required: true
        type: string

jobs:
  chain-specs:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Download Linux partner-chains-node artifact
        uses: actions/download-artifact@v4
        with:
          name: partner-chains-node-x86_64-linux-artifact-artifact
          path: ./

      - name: Generate Chain Specs
        run: |
          chmod +x ./partner-chains-node
          source ./devnet/.envrc
          ./partner-chains-node build-spec --chain local --disable-default-bootnode --raw > devnet_chain_spec.json
          source ./staging/.envrc
          ./partner-chains-node build-spec --chain staging --disable-default-bootnode --raw > staging_chain_spec.json
          source ./staging-preview/.envrc
          ./partner-chains-node build-spec --chain staging-preview --disable-default-bootnode --raw > staging_preview_chain_spec.json
          source ./staging-preprod/.envrc
          ./partner-chains-node build-spec --chain staging-preprod --disable-default-bootnode --raw > staging_preprod_chain_spec.json

      - name: Upload Chain Specs for both chains
        uses: actions/upload-artifact@v4
        with:
          name: chain-specs
          path: |
            devnet_chain_spec.json
            staging_chain_spec.json
            staging_preview_chain_spec.json
            staging_preprod_chain_spec.json
        

