name: "Build and Upload PC Artifacts"
description: "Build and upload partner-chains artifacts for Linux"

inputs:
  sha:
    description: "partner-chains commit SHA or branch to build from"
    required: true
  tag:
    description: "partner-chains release tag to append to artifact name"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.sha }}

    - name: Setup Earthly
      uses: ./.github/earthly-setup
      with:
        SSH_KEY: ${{ env.SUBSTRATE_REPO_SSH_KEY }}
        CONFIG_TAR: ${{ env.EARTHLY_TAR }}

    - name: Build Artifacts with Earthly
      env:
        EARTHLY_CI: true
        EARTHLY_OUTPUT: true
      run: |
        earthly -P +artifacts --PROFILE=production
      shell: bash

    - name: Upload partner-chains-cli artifact
      uses: actions/upload-artifact@v4
      with:
        name: partner-chains-cli-${{ inputs.tag }}-x86_64-linux
        path: partner-chains-cli

    - name: Upload partner-chains-node artifact
      uses: actions/upload-artifact@v4
      with:
        name: partner-chains-node-${{ inputs.tag }}-x86_64-linux
        path: partner-chains-node