name: Deploy ArgoCD Node 

on:
  workflow_call:
    inputs:
      sha:
        description: 'Commit SHA'
        required: true
        type: string

jobs:
  deploy-argocd:
    runs-on: ubuntu-latest 
    permissions:
      id-token: write
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create and Push Manifest
      env:
        GH_TOKEN: ${{ secrets.ACTIONS_PAT }}
      run: |
        cd .github/workflows/modules/deploy/argocd
        bash generate-manifest.sh ${{ inputs.sha }}

    - name: Wait for 12 minutes (ArgoCD refresh interval is 3 minutes + 1 minute to build + 8 minutes for node to start producing blocks)
      run: sleep 720s