name: Build and Upload Artifacts

on:
  workflow_dispatch:
    inputs:
      partner_chains_smart_contracts_sha:
        description: "partner-chains-smart-contracts commit SHA"
        default: "38f4c17e0f4052d885c9d438f7fb8ad0b2e7b25e"
      partner_chains_sha:
        description: "partner-chains commit SHA"
        default: "master"
      partner-chains-tag:
        description: "partner-chains release tag (optional)"
        required: false
      partner-chains-smart-contracts-tag:
        description: "partner-chains-smart-contract release tag (optional)"
        required: false

jobs:
  set-environment:
    runs-on: ubuntu-latest
    outputs:
      partner_chains_cli_x86_64_linux: ${{ steps.set-vars.outputs.partner_chains_cli_x86_64_linux }}
      partner_chains_node_x86_64_linux: ${{ steps.set-vars.outputs.partner_chains_node_x86_64_linux }}
      partner_chains_cli_x86_64_apple_darwin: ${{ steps.set-vars.outputs.partner_chains_cli_x86_64_apple_darwin }}
      partner_chains_node_x86_64_apple_darwin: ${{ steps.set-vars.outputs.partner_chains_node_x86_64_apple_darwin }}
      partner_chains_cli_aarch64_apple_darwin: ${{ steps.set-vars.outputs.partner_chains_cli_aarch64_apple_darwin }}
      partner_chains_node_aarch64_apple_darwin: ${{ steps.set-vars.outputs.partner_chains_node_aarch64_apple_darwin }}
      sidechain_main_cli: ${{ steps.set-vars.outputs.sidechain_main_cli }}
    steps:
      - name: Set environment variables based on inputs
        id: set-vars
        run: |
          if [ -n "${{ github.event.inputs.partner-chains-tag }}" ]; then
            echo "partner_chains_cli_x86_64_linux=partner-chains-cli-${{ github.event.inputs.partner-chains-tag }}-x86_64-linux" >> $GITHUB_ENV
            echo "partner_chains_node_x86_64_linux=partner-chains-node-${{ github.event.inputs.partner-chains-tag }}-x86_64-linux" >> $GITHUB_ENV
            echo "partner_chains_cli_x86_64_apple_darwin=partner-chains-cli-${{ github.event.inputs.partner-chains-tag }}-x86_64-apple-darwin" >> $GITHUB_ENV
            echo "partner_chains_node_x86_64_apple_darwin=partner-chains-node-${{ github.event.inputs.partner-chains-tag }}-x86_64-apple-darwin" >> $GITHUB_ENV
            echo "partner_chains_cli_aarch64_apple_darwin=partner-chains-cli-${{ github.event.inputs.partner-chains-tag }}-aarch64-apple-darwin" >> $GITHUB_ENV
            echo "partner_chains_node_aarch64_apple_darwin=partner-chains-node-${{ github.event.inputs.partner-chains-tag }}-aarch64-apple-darwin" >> $GITHUB_ENV
          else
            echo "partner_chains_cli_x86_64_linux=partner-chains-cli-x86_64-linux" >> $GITHUB_ENV
            echo "partner_chains_node_x86_64_linux=partner-chains-node-x86_64-linux" >> $GITHUB_ENV
            echo "partner_chains_cli_x86_64_apple_darwin=partner-chains-cli-x86_64-apple-darwin" >> $GITHUB_ENV
            echo "partner_chains_node_x86_64_apple_darwin=partner-chains-node-x86_64-apple-darwin" >> $GITHUB_ENV
            echo "partner_chains_cli_aarch64_apple_darwin=partner-chains-cli-aarch64-apple-darwin" >> $GITHUB_ENV
            echo "partner_chains_node_aarch64_apple_darwin=partner-chains-node-aarch64-apple-darwin" >> $GITHUB_ENV
          fi

          if [ -n "${{ github.event.inputs.partner-chains-smart-contracts-tag }}" ]; then
            echo "sidechain_main_cli=sidechain-main-cli-${{ github.event.inputs.partner-chains-smart-contracts-tag }}" >> $GITHUB_ENV
          else
            echo "sidechain_main_cli=sidechain-main-cli" >> $GITHUB_ENV
          fi

  partner-chains-linux:
    runs-on: ubuntu-latest
    needs: set-environment
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.partner_chains_sha }}

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          profile: minimal

      - name: Install protoc
        run: sudo apt-get install -y protobuf-compiler

      - name: Build partner-chains-node
        run: |
          rustup target add x86_64-unknown-linux-gnu
          cargo build -p partner-chains-node --locked --release --target x86_64-unknown-linux-gnu
          cp target/x86_64-unknown-linux-gnu/release/partner-chains-node ${{ needs.set-environment.outputs.partner_chains_node_x86_64_linux }}
          chmod +x ${{ needs.set-environment.outputs.partner_chains_node_x86_64_linux }}

      - name: Build partner-chains-cli
        run: |
          rustup target add x86_64-unknown-linux-gnu
          cargo build -p partner-chains-cli --locked --release --target x86_64-unknown-linux-gnu
          cp target/x86_64-unknown-linux-gnu/release/partner-chains-cli ${{ needs.set-environment.outputs.partner_chains_cli_x86_64_linux }}
          chmod +x ${{ needs.set-environment.outputs.partner_chains_cli_x86_64_linux }}

      - name: Upload partner-chains-cli-x86_64-linux
        uses: actions/upload-artifact@v4
        with:
          name: ${{ needs.set-environment.outputs.partner_chains_cli_x86_64_linux }}
          path: ${{ needs.set-environment.outputs.partner_chains_cli_x86_64_linux }}

      - name: Upload partner-chains-node-x86_64-linux
        uses: actions/upload-artifact@v4
        with:
          name: ${{ needs.set-environment.outputs.partner_chains_node_x86_64_linux }}
          path: ${{ needs.set-environment.outputs.partner_chains_node_x86_64_linux }}

  partner-chains-macos-x86_64:
    runs-on: macos-latest
    needs: set-environment
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.partner_chains_sha }}

      - name: Install protoc
        run: |
          curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v21.3/protoc-21.3-osx-x86_64.zip
          unzip protoc-21.3-osx-x86_64.zip -d $HOME/protoc
          sudo mv $HOME/protoc/bin/protoc /usr/local/bin/protoc

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          profile: minimal

      - name: Build partner-chains-node
        run: |
          rustup target add x86_64-apple-darwin
          cargo build -p partner-chains-node --locked --release --target x86_64-apple-darwin
          cp target/x86_64-apple-darwin/release/partner-chains-node ${{ needs.set-environment.outputs.partner_chains_node_x86_64_apple_darwin }}
          chmod +x ${{ needs.set-environment.outputs.partner_chains_node_x86_64_apple_darwin }}

      - name: Build partner-chains-cli
        run: |
          rustup target add x86_64-apple-darwin
          cargo build -p partner-chains-cli --locked --release --target x86_64-apple-darwin
          cp target/x86_64-apple-darwin/release/partner-chains-cli ${{ needs.set-environment.outputs.partner_chains_cli_x86_64_apple_darwin }}
          chmod +x ${{ needs.set-environment.outputs.partner_chains_cli_x86_64_apple_darwin }}

      - name: Upload partner-chains-cli-x86_64-apple-darwin
        uses: actions/upload-artifact@v4
        with:
          name: ${{ needs.set-environment.outputs.partner_chains_cli_x86_64_apple_darwin }}
          path: ${{ needs.set-environment.outputs.partner_chains_cli_x86_64_apple_darwin }}

      - name: Upload partner-chains-node-x86_64-apple-darwin
        uses: actions/upload-artifact@v4
        with:
          name: ${{ needs.set-environment.outputs.partner_chains_node_x86_64_apple_darwin }}
          path: ${{ needs.set-environment.outputs.partner_chains_node_x86_64_apple_darwin }}

  partner-chains-macos-arm64:
    runs-on: macos-latest
    needs: set-environment
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.partner_chains_sha }}

      - name: Install protoc
        run: |
          curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v21.3/protoc-21.3-osx-aarch_64.zip
          unzip protoc-21.3-osx-aarch_64.zip -d $HOME/protoc
          sudo mv $HOME/protoc/bin/protoc /usr/local/bin/protoc

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          profile: minimal

      - name: Build partner-chains-node
        run: |
          rustup target add aarch64-apple-darwin
          cargo build -p partner-chains-node --locked --release --target aarch64-apple-darwin
          cp target/aarch64-apple-darwin/release/partner-chains-node ${{ needs.set-environment.outputs.partner_chains_node_aarch64_apple_darwin }}
          chmod +x ${{ needs.set-environment.outputs.partner_chains_node_aarch64_apple_darwin }}

      - name: Build partner-chains-cli
        run: |
          rustup target add aarch64-apple-darwin
          cargo build -p partner-chains-cli --locked --release --target aarch64-apple-darwin
          cp target/aarch64-apple-darwin/release/partner-chains-cli ${{ needs.set-environment.outputs.partner_chains_cli_aarch64_apple_darwin }}
          chmod +x ${{ needs.set-environment.outputs.partner_chains_cli_aarch64_apple_darwin }}

      - name: Upload partner-chains-cli-aarch64-apple-darwin
        uses: actions/upload-artifact@v4
        with:
          name: ${{ needs.set-environment.outputs.partner_chains_cli_aarch64_apple_darwin }}
          path: ${{ needs.set-environment.outputs.partner_chains_cli_aarch64_apple_darwin }}
            
      - name: Upload partner-chains-node-aarch64-apple-darwin
        uses: actions/upload-artifact@v4
        with:
          name: ${{ needs.set-environment.outputs.partner_chains_node_aarch64_apple_darwin }}
          path: ${{ needs.set-environment.outputs.partner_chains_node_aarch64_apple_darwin }}

  partner-chains-smart-contracts-build:
    runs-on: [self-hosted, nixos]
    needs: set-environment
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: input-output-hk/partner-chains-smart-contracts
          token: ${{ secrets.ACTIONS_PAT }}
          ref: ${{ github.event.inputs.partner_chains_smart_contracts_sha }}
          path: partner-chains-smart-contracts

      - name: Build
        run: nix build ./partner-chains-smart-contracts#sidechain-release-bundle

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: partner-chains-smart-contracts
          path: result/release.zip

  partner-chains-smart-contracts-process:
    runs-on: ubuntu-latest
    needs: partner-chains-smart-contracts-build
    steps:
      - name: Download release.zip
        uses: actions/download-artifact@v4
        with:
          name: partner-chains-smart-contracts
          path: ./artifact

      - uses: geekyeggo/delete-artifact@v5
        with:
            name: partner-chains-smart-contracts
  
      - name: Unzip release.zip
        run: |
          mkdir -p artifact/unzipped
          unzip artifact/release.zip -d artifact/unzipped
          
      - name: Rename sidechain-cli to sidechain-main-cli
        run: |
          destination_name="${{ needs.set-environment.outputs.sidechain_main_cli }}"
          mv artifact/unzipped/sidechain-cli artifact/unzipped/$destination_name
  
      - name: Upload Renamed Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ needs.set-environment.outputs.sidechain_main_cli }}
          path: artifact/unzipped/${{ needs.set-environment.outputs.sidechain_main_cli }}

