name: CD 

on:
  workflow_dispatch:
    inputs:
      sha:
        description: "partner-chains commit SHA to build from"
        required: true
        type: string
      tag:
        description: "partner-chains release tag"
        required: true
        type: string

permissions:
  id-token: write
  contents: write

env:
  AWS_REGION: "eu-central-1"
  SSH_AUTH_SOCK: /tmp/ssh_agent.sock

jobs:
  build-pc-artifacts:
    runs-on: ubuntu-latest 
    steps:
      - uses: ./.github/workflows/modules/artifacts/build-pc-artifacts.yml
        with:
          sha: ${{ inputs.sha }}
          tag: ${{ inputs.tag }}

  build-and-publish-ecr-image:
    needs: build-pc-artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/modules/images/build-and-publish-ecr-image.yml
        with:
          sha: ${{ inputs.sha }}
          tag: ${{ inputs.tag }}

  partner-chains-smart-contracts:
    uses: ./.github/workflows/modules/artifacts/download-pcsc-artifact.yml
    with:
      sha: ${{ inputs.sha }}

  local-environment-tests:          
    needs: [build-pc-artifacts, partner-chains-smart-contracts]
    uses: ./.github/workflows/modules/tests/local-environment-tests.yml
    with:
      tag: ${{ inputs.tag }}  
      image: ${{ secrets.ECR_REGISTRY_SECRET }}/substrate-node:${{ inputs.sha }}

  create-draft-release:
    uses: ./.github/workflows/modules/release/create-draft-release.yml
    with:
      tag: ${{ inputs.tag }}  
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  chain-specs:
    needs: build-pc-artifacts
    uses: ./.github/workflows/modules/artifacts/generate-chain-specs.yml
    with:
      sha: ${{ inputs.sha }}  

  deploy-staging-preview:
    needs: chain-specs
    uses: ./.github/workflows/modules/deploy/staging-preview-deploy.yml
    with:
      image: ${{ secrets.ECR_REGISTRY_SECRET }}/substrate-node:${{ inputs.sha }}
      chain-spec-secret: staging-preview-chain-spec-${{ inputs.sha }}

  staging-preview-tests: 
    needs: deploy-staging-preview
    uses: ./.github/workflows/modules/tests/staging-preview-tests.yml

  build-and-publish-ghcr-image:
    needs: staging-preview-tests
    uses: ./.github/workflows/modules/images/build-and-publish-ghcr-image.yml
    with:
      sha: ${{ inputs.sha }}
      tag: ${{ inputs.tag }}

  publish-release:
    needs: staging-preview-tests
    uses: ./.github/workflows/modules/release/publish-release.yml
    with:
      tag: ${{ inputs.tag }}  
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy-staging-preprod:
    needs: staging-preview-tests
    uses: ./.github/workflows/modules/deploy/staging-preprod-deploy.yml
    with:
      image: ${{ secrets.ECR_REGISTRY_SECRET }}/substrate-node:${{ inputs.sha }}
      chain-spec-secret: staging-preprod-chain-spec-${{ inputs.sha }}

  staging-preprod-tests: 
    needs: deploy-staging-preprod
    uses: ./.github/workflows/modules/tests/staging-preprod-tests.yml