name: CI 

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - '**' 
  workflow_dispatch:
    inputs:
      upload:
        description: "Upload the container to our registry"
        default: false
        type: boolean
      repository:
        description: "GitHub repository name (e.g., username/repo)"
        required: true
        default: 'input-output-hk/partner-chains'
      branch:
        description: "Branch name to build"
        required: true
        default: 'master'
      rustdoc:
        description: "Build and publish the rustdoc"
        default: false
        type: boolean
  repository_dispatch:
    types: [test-run-pr]

env:
  AWS_REGION: "eu-central-1"
  AWS_DEFAULT_REGION: "eu-central-1"
  SSH_AUTH_SOCK: /tmp/ssh_agent.sock

jobs:
  earthly-build-and-push:
      uses: ./.github/workflows/modules/artifacts/earthly-build-and-push.yml
      with:
        repository: ${{ github.repository }}
        branch: ${{ github.head_ref }}
        upload: 'true'
      secrets:
        SUBSTRATE_REPO_SSH_KEY: ${{ secrets.SUBSTRATE_REPO_SSH_KEY }}
        EARTHLY_TAR: ${{ secrets.EARTHLY_TAR }}
        AWS_ROLE_ARN_SECRET: ${{ secrets.AWS_ROLE_ARN_SECRET }}
        ECR_REGISTRY_SECRET: ${{ secrets.ECR_REGISTRY_SECRET }}

  deploy-argocd:
      needs: build-and-push
      if: ${{ github.event.pull_request.merged == true && !contains(github.event.pull_request.labels.*.name, 'ci-off') }}
      uses: ./.github/workflows/modules/deploy/argocd/deploy-argocd.yml
      with:
        sha: ${{ github.sha }}

  argocd-tests:
    needs: deploy-argocd
    uses: ./.github/workflows/modules/tests/argocd-tests.yml
    with:
      node-host: sha-${{ github.sha }}-service.integration-testing.svc.cluster.local
      node-port: 9933
    secrets: inherit

  teardown-argocd:
      needs: [build-and-push, deploy-argocd, argocd-tests]
      if: ${{ always() && needs.generate-manifest.result == 'success' }}
      uses: ./.github/workflows/modules/deploy/teardown-argocd.yml
      with:
        sha: ${{ github.sha }}

  upload-chain-specs:
    needs: [build-and-push]
    if: ${{ github.ref_name == 'master' || inputs.upload == 'true' }}
    uses: ./.github/workflows/modules/deploy/upload-chain-specs.yml
    with:
      sha: ${{ github.sha }}

  deploy-rustdoc:
    if: ${{ github.event_name != 'workflow_dispatch' || inputs.rustdoc == 'true' }}
    uses: ./.github/workflows/modules/deploy/deploy-rustdoc.yml
    with:
      ssh_key: ${{ secrets.SUBSTRATE_REPO_SSH_KEY }}
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

   devshell-tests:
     permissions:
       id-token: write
       contents: read
     uses: ./.github/workflows/modules/tests/devshell-tests.yml
     secrets:
       AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
       NIX_SIGNING_KEY: ${{ secrets.NIX_SIGNING_KEY }}
       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
       AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
    
