name: CI 

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - '**' 

permissions:
  id-token: write
  contents: write

env:
  AWS_REGION: "eu-central-1"
  SSH_AUTH_SOCK: /tmp/ssh_agent.sock

jobs:
  earthly-build-and-push:
    permissions:
      id-token: write
      contents: write
    uses: ./.github/workflows/earthly-build-and-push.yml
    with:
      repository: ${{ github.repository }}
      branch: ${{ github.ref }}
      upload: 'true'
    secrets:
      SUBSTRATE_REPO_SSH_KEY: ${{ secrets.SUBSTRATE_REPO_SSH_KEY }}
      EARTHLY_TAR: ${{ secrets.EARTHLY_TAR }}
      AWS_ROLE_ARN_SECRET: ${{ secrets.AWS_ROLE_ARN_SECRET }}
      ECR_REGISTRY_SECRET: ${{ secrets.ECR_REGISTRY_SECRET }}

  devshell-tests:
    permissions:
      id-token: write
      contents: write
    strategy:
      matrix:
        os: [nixos, macos]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Nix Devshells Tests
        uses: ./.github/actions/tests/devshell-tests
        env:
          AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
          NIX_SIGNING_KEY: ${{ secrets.NIX_SIGNING_KEY }}
          AWS_REGION: "eu-central-1"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

  deploy-argocd:
    permissions:
      id-token: write
      contents: write
    needs: earthly-build-and-push
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Deploy ArgoCD Node
        uses: ./.github/actions/deploy/argocd/deploy-argocd
        with:
          sha: ${{ github.sha }}
        env:
          ACTIONS_PAT: ${{ secrets.ACTIONS_PAT }}

  argocd-tests:
    permissions:
      id-token: write
      contents: write
    needs: deploy-argocd
    runs-on: [self-hosted, eks]
    steps:
      - name: Run Tests
        uses: ./.github/actions/tests/run-k8-tests
        with:
          node-host: sha-${{ github.sha }}-service.integration-testing.svc.cluster.local
          node-port: 9933
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          AWS_ROLE_ARN_: ${{ secrets.AWS_ROLE_ARN_ }}
          SSH_KEY_BINARY_HOST: ${{ secrets.SSH_KEY_BINARY_HOST }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          JIRA_URL: ${{ secrets.JIRA_URL }}
          ACTIONS_PAT: ${{ secrets.ACTIONS_PAT }}

  teardown-argocd:
    permissions:
      id-token: write
      contents: write
    needs: [earthly-build-and-push, deploy-argocd, argocd-tests]
    runs-on: ubuntu-latest
    steps:
      - name: Teardown ArgoCD Environment
        uses: ./.github/actions/deploy/argocd/teardown-argocd
        with:
          sha: ${{ github.sha }}
        env:
          ACTIONS_PAT: ${{ secrets.ACTIONS_PAT }}

  upload-chain-specs:
    permissions:
      id-token: write
      contents: write
    needs: [earthly-build-and-push]
    if: github.event.pull_request.merged == true
    runs-on: [self-hosted, eks]
    steps:
      - name: Upload chain spec artifacts to Kubernetes
        uses: ./.github/actions/upload-chain-specs
        with:
          sha: ${{ github.sha }}
        env:
          kubeconfig_base64: ${{ secrets.kubeconfig_base64 }}
          K8S_SERVER: ${{ secrets.K8S_SERVER }}
          K8S_SA_TOKEN: ${{ secrets.K8S_SA_TOKEN }}

  deploy-rustdoc:
    permissions:
      id-token: write
      contents: write
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Deploy Rust Docs
        uses: ./.github/actions/deploy/deploy-rustdoc
        with:
          ssh_key: ${{ secrets.SUBSTRATE_REPO_SSH_KEY }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock

    
